---
abstract: Perl Based Secure Distributed Computing Network Process
author: 'Brian M. Kelly <Brian.Kelly@fullautosoftware.net>'
distribution_type: module
generated_by: Module::Install version 0.67
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-FullAuto
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::CBC: 0
  Crypt::DES: 0
  Cwd: 0
  DB_File: 0
  English: 0
  Fcntl: 0
  Getopt::Long: 0
  HTTP::Date: 0
  IO::Handle: 0
  IO::Pty: 0
  IO::Select: 0
  LWP: 0
  MLDBM: 0
  MLDBM::Sync: 0
  MLDBM::Sync::SDBM_File: 0
  Mail::Internet: 0
  Mail::Sender: 0
  Net::Telnet: 0
  POSIX: 0
  Pod::Usage: 0
  Socket: 0
  Symbol: 0
  Sys::Hostname: 0
  Term::Menus: 0
  Term::ReadKey: 0
  Tie::Cache: 0
  Time::Local: 0
  URI: 0
  version: 0
version: 0.01
