---
name: Net-FullAuto
version: 0.12
author:
  - 'Brian M. Kelly <Brian.Kelly@fullautosoftware.net>'
abstract: Perl Based Secure Distributed Computing Network Process
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
requires:
  Crypt::CBC: 0
  Crypt::DES: 0
  Getopt::Long: 0
  HTTP::Date: 0
  IO::Pty: 0
  LWP: 0
  MLDBM: 0
  MLDBM::Sync: 0
  MLDBM::Sync::SDBM_File: 0
  Mail::Internet: 0
  Mail::Sender: 0
  MemHandle: 0
  Net::Telnet: 0
  Sort::Versions: 0
  Term::Menus: 1.24
  Tie::Cache: 0
  URI: 0
recommends:
  Crypt::Rijndael: 0
provides:
  File_Transfer:
    file: lib/Net/FullAuto/FA_lib.pm
  Net::FullAuto:
    file: lib/Net/FullAuto.pm
    version: 0.12
  Net::FullAuto::FA_DB:
    file: lib/Net/FullAuto/FA_lib.pm
  Net::FullAuto::FA_lib:
    file: lib/Net/FullAuto/FA_lib.pm
  Net::FullAuto::Getline:
    file: lib/Net/FullAuto/FA_lib.pm
  Net::FullAuto::MemoryHandle:
    file: lib/Net/FullAuto/FA_lib.pm
  Rem_Command:
    file: lib/Net/FullAuto/FA_lib.pm
  fa_hosts:
    file: lib/Net/FullAuto/fa_hosts.pm
    version: 1
  fa_maps:
    file: lib/Net/FullAuto/fa_maps.pm
    version: 1
  menu_cfg:
    file: lib/Net/FullAuto/menu_cfg.pm
    version: 1
  usr_code:
    file: lib/Net/FullAuto/usr_code.pm
    version: 1
generated_by: Module::Build version 0.280802
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
