---
abstract: 'Perl Based Secure Distributed Computing Network Process'
author:
  - 'Brian M. Kelly <Brian.Kelly@fullautosoftware.net>'
configure_requires:
license: gpl-3.0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-FullAuto
provides:
  Bad_Handle:
    file: lib/Net/FullAuto/FA_Core.pm
  File_Transfer:
    file: lib/Net/FullAuto/FA_Core.pm
  Net::FullAuto:
    file: lib/Net/FullAuto.pm
    version: 0.99999953
  Net::FullAuto::FA_Core:
    file: lib/Net/FullAuto/FA_Core.pm
  Net::FullAuto::FA_DB:
    file: lib/Net/FullAuto/FA_Core.pm
  Net::FullAuto::Getline:
    file: lib/Net/FullAuto/FA_Core.pm
  Net::FullAuto::MemoryHandle:
    file: lib/Net/FullAuto/FA_Core.pm
  Rem_Command:
    file: lib/Net/FullAuto/FA_Core.pm
  fa_code:
    file: lib/Net/FullAuto/Distro/fa_code.pm
  fa_conf:
    file: lib/Net/FullAuto/Distro/fa_conf.pm
  fa_host:
    file: lib/Net/FullAuto/Distro/fa_host.pm
  fa_maps:
    file: lib/Net/FullAuto/Distro/fa_maps.pm
  fa_menu:
    file: lib/Net/FullAuto/Distro/fa_menu.pm
recommends:
  Crypt::Rijndael: 0
requires:
  Module::Build: .3601
  Module::Load::Conditional: 0
#  Data::Dump::Streamer: 0
#  Term::Menus: 2.49
  Tie::Cache: 0
  Sort::Versions: 0
  Crypt::CBC: 0
  Crypt::DES: 0
  Digest::MD5: 0
  Digest::SHA: 0
  HTTP::Date: 0
  JSON: 2.14
  IO::Pty: 1.09
  IO::Capture::Stderr: 0
  IO::CaptureOutput: 0
  Capture::Tiny: 0
  Net::Telnet: 0
  Test::Deep : 0
  Term::RawInput : 0
  Term::ReadKey: 0
  URI: 0
  Email::Sender: 0
  MIME::Entity: 0
  String::Random: 0
  Data::Password::Check: 0
  BerkeleyDB: 0
  Cache::Cache: 0
  CHI: 0
  ExtUtils::MakeMaker: 6.59
  ExtUtils::CBuilder: 0
  PPI: 0
  YAML: 0
resources:
  license: http://opensource.org/licenses/gpl-3.0.html
version: 0.99999953
