---
abstract: 'Perl Based Secure Distributed Computing Network Process'
author:
  - 'Brian M. Kelly <Brian.Kelly@fullautosoftware.net>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-FullAuto
provides:
  Bad_Handle:
    file: lib/Net/FullAuto/FA_Core.pm
  File_Transfer:
    file: lib/Net/FullAuto/FA_Core.pm
  Net::FullAuto:
    file: lib/Net/FullAuto.pm
    version: 0.50
  Net::FullAuto::FA_Core:
    file: lib/Net/FullAuto/FA_Core.pm
  Net::FullAuto::FA_DB:
    file: lib/Net/FullAuto/FA_Core.pm
  Net::FullAuto::Getline:
    file: lib/Net/FullAuto/FA_Core.pm
  Net::FullAuto::MemoryHandle:
    file: lib/Net/FullAuto/FA_Core.pm
  Rem_Command:
    file: lib/Net/FullAuto/FA_Core.pm
  fa_code:
    file: lib/Net/FullAuto/Distro/fa_code.pm
    version: 1
  fa_conf:
    file: lib/Net/FullAuto/Distro/fa_conf.pm
    version: 1
  fa_host:
    file: lib/Net/FullAuto/Distro/fa_host.pm
    version: 1
  fa_maps:
    file: lib/Net/FullAuto/Distro/fa_maps.pm
    version: 1
  fa_menu:
    file: lib/Net/FullAuto/Distro/fa_menu.pm
    version: 1
recommends:
  Crypt::Rijndael: 0
requires:
  Crypt::CBC: 0
  Crypt::DES: 0
  Getopt::Long: 0
  HTTP::Date: 0
  IO::Capture::Stderr: 0
  IO::CaptureOutput: 0
  IO::Pty: 0
  MLDBM: 0
  MLDBM::Sync: 0
  MLDBM::Sync::SDBM_File: 0
  Mail::Internet: 0
  Mail::Sender: 0
  Net::Telnet: 0
  Sort::Versions: 0
  Term::Menus: 1.49
  Term::ReadKey: 0
  Tie::Cache: 0
  URI: 0
  DB_File: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.50
